[2023-02-22T21:13:33.760+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: db_to_csv.db_to_csv_dag manual__2023-02-22T21:13:31.845674+00:00 [queued]>
[2023-02-22T21:13:33.775+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: db_to_csv.db_to_csv_dag manual__2023-02-22T21:13:31.845674+00:00 [queued]>
[2023-02-22T21:13:33.776+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T21:13:33.777+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-22T21:13:33.778+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T21:13:33.787+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): db_to_csv_dag> on 2023-02-22 21:13:31.845674+00:00
[2023-02-22T21:13:33.794+0000] {standard_task_runner.py:55} INFO - Started process 300 to run task
[2023-02-22T21:13:33.802+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'db_to_csv', 'db_to_csv_dag', 'manual__2023-02-22T21:13:31.845674+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/schedule.py', '--cfg-path', '/tmp/tmpth6p3zav']
[2023-02-22T21:13:33.803+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask db_to_csv_dag
[2023-02-22T21:13:33.883+0000] {task_command.py:388} INFO - Running <TaskInstance: db_to_csv.db_to_csv_dag manual__2023-02-22T21:13:31.845674+00:00 [running]> on host fd37b4f3bb6b
[2023-02-22T21:13:33.947+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=db_to_csv
AIRFLOW_CTX_TASK_ID=db_to_csv_dag
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T21:13:31.845674+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-22T21:13:31.845674+00:00
[2023-02-22T21:13:33.950+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-22T21:13:33.952+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 extract_to_csv.py']
[2023-02-22T21:13:33.964+0000] {subprocess.py:86} INFO - Output:
[2023-02-22T21:13:34.041+0000] {subprocess.py:93} INFO - python3: can't open file 'extract_to_csv.py': [Errno 2] No such file or directory
[2023-02-22T21:13:34.043+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-22T21:13:34.056+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-22T21:13:34.060+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=db_to_csv, task_id=db_to_csv_dag, execution_date=20230222T211331, start_date=20230222T211333, end_date=20230222T211334
[2023-02-22T21:13:34.071+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task db_to_csv_dag (Bash command failed. The command returned a non-zero exit code 2.; 300)
[2023-02-22T21:13:34.094+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-22T21:13:34.111+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
