[2023-02-23T00:00:00.739+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: scrap_metadata.extract_geos_metadata scheduled__2023-02-22T00:00:00+00:00 [queued]>
[2023-02-23T00:00:00.748+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: scrap_metadata.extract_geos_metadata scheduled__2023-02-22T00:00:00+00:00 [queued]>
[2023-02-23T00:00:00.749+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T00:00:00.751+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-23T00:00:00.752+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T00:00:00.765+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): extract_geos_metadata> on 2023-02-22 00:00:00+00:00
[2023-02-23T00:00:00.774+0000] {standard_task_runner.py:55} INFO - Started process 9932 to run task
[2023-02-23T00:00:00.780+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrap_metadata', 'extract_geos_metadata', 'scheduled__2023-02-22T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/schedule.py', '--cfg-path', '/tmp/tmpszxl3vw8']
[2023-02-23T00:00:00.783+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask extract_geos_metadata
[2023-02-23T00:00:00.868+0000] {task_command.py:388} INFO - Running <TaskInstance: scrap_metadata.extract_geos_metadata scheduled__2023-02-22T00:00:00+00:00 [running]> on host fd37b4f3bb6b
[2023-02-23T00:00:00.946+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=scrap_metadata
AIRFLOW_CTX_TASK_ID=extract_geos_metadata
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-22T00:00:00+00:00
[2023-02-23T00:00:00.949+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-23T00:00:00.951+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 aws_geos.py']
[2023-02-23T00:00:00.965+0000] {subprocess.py:86} INFO - Output:
[2023-02-23T00:00:01.041+0000] {subprocess.py:93} INFO - python3: can't open file 'aws_geos.py': [Errno 2] No such file or directory
[2023-02-23T00:00:01.044+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-23T00:00:01.069+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-23T00:00:01.074+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=scrap_metadata, task_id=extract_geos_metadata, execution_date=20230222T000000, start_date=20230223T000000, end_date=20230223T000001
[2023-02-23T00:00:01.086+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 27 for task extract_geos_metadata (Bash command failed. The command returned a non-zero exit code 2.; 9932)
[2023-02-23T00:00:01.111+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T00:00:01.137+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
