[2023-03-02T02:09:43.344+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_nexrad_data scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T02:09:43.355+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_nexrad_data scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T02:09:43.357+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T02:09:43.357+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T02:09:43.358+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T02:09:43.369+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_nexrad_data> on 2023-03-01 00:00:00+00:00
[2023-03-02T02:09:43.383+0000] {standard_task_runner.py:55} INFO - Started process 254 to run task
[2023-03-02T02:09:43.398+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'scrape_nexrad_data', 'scheduled__2023-03-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/scrapper.py', '--cfg-path', '/tmp/tmpqb0jqb07']
[2023-03-02T02:09:43.401+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask scrape_nexrad_data
[2023-03-02T02:09:43.546+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.scrape_nexrad_data scheduled__2023-03-01T00:00:00+00:00 [running]> on host 5d83bf79023b
[2023-03-02T02:09:43.661+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=scrape_nexrad_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-01T00:00:00+00:00
[2023-03-02T02:11:34.176+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrapper.py", line 134, in NEXRAD_scrap_load
    (row[0], row[1], row[2], row[3], row[4]))
psycopg2.errors.UndefinedTable: relation "metadata_nexrad" does not exist
LINE 1: INSERT INTO metadata_nexrad (id, year, month, day, station) ...
                    ^

[2023-03-02T02:11:34.243+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=scrape_nexrad_data, execution_date=20230301T000000, start_date=20230302T020943, end_date=20230302T021134
[2023-03-02T02:11:34.308+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task scrape_nexrad_data (relation "metadata_nexrad" does not exist
LINE 1: INSERT INTO metadata_nexrad (id, year, month, day, station) ...
                    ^
; 254)
[2023-03-02T02:11:34.416+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T02:11:34.468+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
