[2023-03-03T07:50:38.264+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.fetch_nexrad_stations manual__2023-03-03T07:50:32.360111+00:00 [queued]>
[2023-03-03T07:50:38.310+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.fetch_nexrad_stations manual__2023-03-03T07:50:32.360111+00:00 [queued]>
[2023-03-03T07:50:38.314+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T07:50:38.325+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-03T07:50:38.328+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T07:50:38.390+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fetch_nexrad_stations> on 2023-03-03 07:50:32.360111+00:00
[2023-03-03T07:50:38.445+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'fetch_nexrad_stations', 'manual__2023-03-03T07:50:32.360111+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/scrapper.py', '--cfg-path', '/tmp/tmp5ea0uh1l']
[2023-03-03T07:50:38.420+0000] {standard_task_runner.py:55} INFO - Started process 479 to run task
[2023-03-03T07:50:38.449+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask fetch_nexrad_stations
[2023-03-03T07:50:38.674+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.fetch_nexrad_stations manual__2023-03-03T07:50:32.360111+00:00 [running]> on host 951056ee0f21
[2023-03-03T07:50:38.822+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=fetch_nexrad_stations
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T07:50:32.360111+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-03T07:50:32.360111+00:00
[2023-03-03T07:50:40.196+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrapper.py", line 174, in nexrad_stations
    station.to_csv(f"/opt/airflow/working_dir/data/nexrad-stations.csv", sep=',', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/working_dir/data/nexrad-stations.csv'
[2023-03-03T07:50:40.277+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=fetch_nexrad_stations, execution_date=20230303T075032, start_date=20230303T075038, end_date=20230303T075040
[2023-03-03T07:50:40.312+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task fetch_nexrad_stations ([Errno 2] No such file or directory: '/opt/airflow/working_dir/data/nexrad-stations.csv'; 479)
[2023-03-03T07:50:40.398+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-03T07:50:40.438+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
