[2023-02-22T23:34:36.177+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: scrap_metadata.extract_geos_metadata manual__2023-02-22T23:29:37.865560+00:00 [queued]>
[2023-02-22T23:34:36.233+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: scrap_metadata.extract_geos_metadata manual__2023-02-22T23:29:37.865560+00:00 [queued]>
[2023-02-22T23:34:36.238+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T23:34:36.242+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-02-22T23:34:36.244+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T23:34:36.274+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): extract_geos_metadata> on 2023-02-22 23:29:37.865560+00:00
[2023-02-22T23:34:36.289+0000] {standard_task_runner.py:55} INFO - Started process 8348 to run task
[2023-02-22T23:34:36.305+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrap_metadata', 'extract_geos_metadata', 'manual__2023-02-22T23:29:37.865560+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/schedule.py', '--cfg-path', '/tmp/tmph326uygy']
[2023-02-22T23:34:36.336+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask extract_geos_metadata
[2023-02-22T23:34:36.671+0000] {task_command.py:388} INFO - Running <TaskInstance: scrap_metadata.extract_geos_metadata manual__2023-02-22T23:29:37.865560+00:00 [running]> on host fd37b4f3bb6b
[2023-02-22T23:34:36.916+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=scrap_metadata
AIRFLOW_CTX_TASK_ID=extract_geos_metadata
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T23:29:37.865560+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-22T23:29:37.865560+00:00
[2023-02-22T23:34:36.934+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-22T23:34:36.938+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/../../aws_geos.py ']
[2023-02-22T23:34:36.963+0000] {subprocess.py:86} INFO - Output:
[2023-02-22T23:34:37.083+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/dags/../../aws_geos.py': [Errno 2] No such file or directory
[2023-02-22T23:34:37.087+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-22T23:34:37.105+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-22T23:34:37.111+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=scrap_metadata, task_id=extract_geos_metadata, execution_date=20230222T232937, start_date=20230222T233436, end_date=20230222T233437
[2023-02-22T23:34:37.131+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task extract_geos_metadata (Bash command failed. The command returned a non-zero exit code 2.; 8348)
[2023-02-22T23:34:37.190+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-22T23:34:37.234+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
